language: php

sudo: false

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer install --prefer-dist

script: bin/phpunit

env:
  global:
    - secure: "jLeBWhlYZqc5aXAxtUd+xn4SN4sTacqs/mrrX//QMLld3JnXAuweFI1rlJseI0n3sCjqQeDiHlKtwqdnIMO+iRssBkBUQJsjMOZZZn2RVGqyCh+/Xa4lSEp3uLTdog0EoRS8XA7GraSPC/kT1swANkgJhRI/EdwvpQdcpiFROdk="

before_install:
  - composer config github-oauth.github.com $GITHUB_TOKEN
